version: '3'

tasks:
  default:
    cmds:
      - task --list
  
  server:
    cmds:
      - CGO_ENABLED=0 go build
    sources:
      - main.go
      - config/*
      - model/*
      - sticky/*
      - web/*
      - web/client/elm.js
      - web/client/index.html
      - web/static/*/*
      
    generates:
      - timer
    
    deps:
      - client

  server-prod:
    cmds:
      - CGO_ENABLED=0 go build
    sources:
      - main.go
      - config/*
      - model/*
      - sticky/*
      - web/*
      - web/client/elm.js
      - web/client/index.html
      - web/static/*/*
      
    generates:
      - timer
    
    deps:
      - client-prod

  client:
    dir: web/client
    cmds:
      - elm make src/Main.elm --output elm.js
    sources:
      - elm.json
      - src/*.elm
      - src/**/*.elm
      - index.html
    generates:
      - elm.js

  client-prod:
    dir: web/client
    cmds:
      - elm make src/Main.elm --optimize --output elm.js
      - uglifyjs elm.js --compress 'pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output elm.js
    sources:
      - elm.json
      - src/*.elm
      - src/**/*.elm
      - index.html
    generates:
      - elm.js

  build:
    deps:
      - server
  
  prod:
    cmds:
      - task: client-prod
      - task: server-prod
  

  start:
    desc: |
      Starts the server. 
      
        Use --watch to restart the server if the source changes.

        task start --watch

    deps: 
      - server
      - client

    cmds:
    - ./timer

    method: none

    ignore_error: true


  clean:
    desc: Removes all generated files
    cmds:
      - git clean -xf
